# Generated by Django 2.0.5 on 2018-05-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(None), to='blogapp.Category'),
        ),
    ]
