# Generated by Django 2.0.5 on 2018-06-04 08:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20180601_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='full text'),
        ),
    ]
