# Generated by Django 2.0.5 on 2018-06-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
